print("Welcome to the tip calculator!")
bill=input("what was the total bill? $")
bill_as_float=float(bill)
tip=input("How much % tip would you like to give? 10, 12, or 15?")
tip_as_int=int(tip)
billSPLIT=input("How many people to split the bill?")
split_as_int=int(billSPLIT)
totalBILL= bill_as_float + (bill_as_float * (tip_as_int/100))
afterSPLIT= round(totalBILL/split_as_int,2)
print(f"Each person should pay: ${afterSPLIT}")
